config/routes.rb
Rails.application.routes.draw do
  get "/products", to: "products#index"
  get "/products/:id", to: "products#show", as: "product"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, presence: true
  validates :price, presence: true
  validates :stock_quantity, presence: true
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
include ActionView::Helpers::NumberHelper

class ProductsController < ApplicationController
  def index
    @products = Product.includes(:category).all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">

<div class="container mt-4">
  <h1 class="mb-4">All Products</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Price</th>
        <th>Stock Quantity</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= link_to product.title, product_path(product) %></td>
          <td><%= product.description %></td>
          <td>$<%= product.price %></td>
          <td class="text-center"><%= product.stock_quantity %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/products/show.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">


<div class="container mt-4">
  <h1><%= @product.title %></h1>

  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Description</h5>
      <p class="card-text"><%= @product.description %></p>
    </div>
  </div>

  <ul class="list-group mt-3">
    <li class="list-group-item"><strong>Price:</strong> $<%= number_with_precision(@product.price, precision: 2) %></li>
    <li class="list-group-item"><strong>Stock Quantity:</strong> <%= @product.stock_quantity %></li>
  </ul>
  <br>
  <a href="<%= products_path %>" class="btn btn-secondary mb-3">Back</a>
</div>